In [1]:
import numpy as np

In [4]:
arr_1D=np.array([1,2,3,4])
print(arr_1D)

[1 2 3 4]


In [5]:
type(arr_1D)

numpy.ndarray

In [6]:
arr_1D.ndim




1

In [7]:
arr_2D=np.array([[1,2,3,4],
               [2,3,45,5],
               [6,7,8,9]])

In [8]:
type(arr_2D)

numpy.ndarray

In [10]:
arr_2D.ndim


2

In [11]:
print(arr_2D)

[[ 1  2  3  4]
 [ 2  3 45  5]
 [ 6  7  8  9]]


In [12]:
arr_2D.size

12

In [13]:
arr_2D.shape

(3, 4)

In [14]:
#(row,coloum)

In [16]:
arr_2D.dtype

dtype('int32')