In [1]:
import numpy as np

In [3]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [5]:
list1 = [2,3,4,56,6]
list2 = [8,7,90,80,70]
list3 = list1+list2
print(list3)

[2, 3, 4, 56, 6, 8, 7, 90, 80, 70]


In [8]:
arr3 = np.concatenate((arr1 , arr2))
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [9]:
arr3.ndim

2

In [10]:
arr4 = np.concatenate((arr1 , arr2) , axis = 1)

In [11]:
print(arr4)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [13]:
np.vstack((arr1 , arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
np.hstack((arr1 , arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [18]:
arr5 = np.hstack((arr1 , arr2 , arr4))
print(arr5)

[[ 1  2  3  4 17 18 19 20  1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24  5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28  9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32 13 14 15 16 29 30 31 32]]


In [17]:
# split function:


In [30]:
list4 = np.split(arr5 , 2)
print(list4)

[array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24]]), array([[ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])]


In [24]:
list4[0]

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24]])

In [32]:
type(list4)


list

In [33]:
type(list4[0])

numpy.ndarray

In [36]:
arr6 = np.array([1,2,3,4,5,6])
print(arr6)

[1 2 3 4 5 6]


In [37]:
np.split(arr6 , [1 , 4])

[array([1]), array([2, 3, 4]), array([5, 6])]