In [3]:
import numpy as np

In [4]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
#ones matrix

In [7]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [8]:
mx_1s.dtype

dtype('float64')

In [9]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
mx_1s=np.ones((3,4),dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
#zero's matrix

In [14]:
mx_0s=np.zeros((3,4),dtype = int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
mx_0s=np.zeros((3,4),dtype = bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [16]:
mx_0s=np.zeros((3,4),dtype = str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [18]:
em_str = ''
print(bool(em_str))

False


In [19]:
em=np.empty((3,3))
print(em)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 2.98415650e-321]
 [3.44886448e-307 1.11259601e-306 2.04721870e-306]]


In [ ]:
#empty matrix