numpy functions

In [1]:
import numpy as np

In [2]:
#arange()

In [3]:
#np.arange(start,end,steps)

In [4]:
arr_1D=np.arange(1,13)
print(arr_1D)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
arr_1D=np.arange(1,13,2)
print(arr_1D)

[ 1  3  5  7  9 11]


In [6]:
#linspace()
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [7]:
#reshape():convert one dimentional array to 2d or 3d
arr_2d=arr_1D.reshape(2,3)
print(arr_2d)

[[ 1  3  5]
 [ 7  9 11]]


In [8]:
ar = np.arange(1,13).reshape(2,3,2)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
#ravel():convert multidimentional array into one dimentional array
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
#flatten():do same as above
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
#transpose():converts rows in to column
arr_2d.transpose()

array([[ 1,  7],
       [ 3,  9],
       [ 5, 11]])

In [12]:
arr_2d.T


array([[ 1,  7],
       [ 3,  9],
       [ 5, 11]])