# Random Sampling with python

In [1]:
import numpy as np
import random 

In [2]:
np.random.random(1)

array([0.46452505])

In [4]:
np.random.random((3,3)) # random values between 0 and 1

array([[0.56891346, 0.41112015, 0.30174571],
       [0.42607226, 0.87247067, 0.89310404],
       [0.41336623, 0.67900873, 0.51378971]])

In [5]:
np.random.randint(1,5)

4

In [7]:
np.random.randint(1,5,(3,3))

array([[2, 1, 4],
       [4, 2, 3],
       [1, 2, 4]])

In [8]:
np.random.randint(1,5,(2,3,3))

array([[[2, 3, 3],
        [3, 1, 1],
        [4, 3, 1]],

       [[4, 2, 1],
        [3, 3, 4],
        [3, 2, 4]]])

In [9]:
np.random.seed(11)
np.random.randint(1,5,(2,3,3))


array([[[2, 4, 1],
        [4, 2, 4],
        [2, 1, 2]],

       [[4, 3, 1],
        [2, 1, 1],
        [2, 1, 2]]])

In [10]:
np.random.seed(11)
np.random.randint(1,5,(2,3,3))


array([[[2, 4, 1],
        [4, 2, 4],
        [2, 1, 2]],

       [[4, 3, 1],
        [2, 1, 1],
        [2, 1, 2]]])

In [11]:
np.random.rand(3,3)# values between 0 and 1

array([[0.85079509, 0.72996447, 0.10873607],
       [0.89390417, 0.85715425, 0.16508662],
       [0.63233401, 0.02048361, 0.11673727]])

In [12]:
np.random.randn(3,3) # return sample of standard normal distribution

array([[-0.88623967, -0.47573349,  0.68968231],
       [ 0.56119218, -1.30554851, -1.11947526],
       [ 0.73683739,  1.57463407, -0.03107509]])

In [13]:
x = [1,2,3,4]
np.random.choice(x)

4

In [14]:
np.random.choice(x)

1

In [16]:
for i in range(20):
  print(np.random.choice(x))

4
2
2
4
3
4
4
2
1
4
1
4
2
1
1
3
1
3
4
2


In [17]:
x

[1, 2, 3, 4]

In [18]:
np.random.permutation(x)

array([4, 1, 3, 2])

In [19]:
np.random.permutation(x)

array([1, 3, 2, 4])